compile error handling

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,16 +1,32 @@
 #!/bin/bash
 
-# STASH_NAME="pre-commit-$(date +%s)"
-# git stash save -q --keep-index $STASH_NAME
+STASH_NAME="pre-commit-$(date +%s)"
+git stash save -q --keep-index $STASH_NAME
 
 CHANGED_DTHS=$(git diff --cached --name-only | grep .*.groovy)
-echo $CHANGED_DTHS
-ERRORS = $(groovyc $CHANGED_DTHS 2>&1 | grep ".groovy:")
-echo $ERRORS
+ERROR_COUNT=0
+# echo $CHANGED_DTHS
+while IFS= read -r DTH; do
+  echo "Verifying $DTH"
+  ERRORS=$(groovyc $DTH 2>&1 | grep ".groovy:")
+  # echo $ERRORS
+  IMPORTANT_ERRORS=$(echo $ERRORS | grep -v "unable")
+  if [[ ${#IMPORTANT_ERRORS} -eq 0 ]]; then
+    echo "No disqualifying compilation errors found"
+  else
+    echo "$DTH failed to compile, run groovyc on your source file for the full error: $ERRORS"
+    ERROR_COUNT=$((ERROR_COUNT + 1))
+  fi
+  echo "======================================================================="
+done < <(git diff --cached --name-only | grep .*.groovy)
 
-# STASHES=$(git stash list)
-# if [[ $STASHES == "$STASH_NAME" ]]; then
-#   git stash pop -q
-# fi
+STASHES=$(git stash list)
+if [[ $STASHES == "$STASH_NAME" ]]; then
+  git stash pop -q
+fi
 
-#echo "rejected" && exit 1
+if [[ $ERROR_COUNT -gt 0 ]]; then
+  echo "rejected" && exit 1
+else
+  exit 0
+fi
